### ISSUE TITLE
Repository installation

### ISSUE THREAD

**Issue by italomato** [luxrck/GamepadTweaks#1]
Hey there! I would like to ask how I could install the GamepadTweaks. I tried inserting the repository link (https://github.com/luxrck/GamepadTweaks/blob/master/repo.json), but the launcher says the download failed.
From the description, it's an amazing feature to healers who play on controllers. Thank you for all the work!

**Comment by luxrck** [comment]
This plugin is unstable and may change very frequently. So I have deleted those obsolete builds.

Goto [Actions] Tab -> Select latest build -> Download artifacts -> Install as a dev plugin([see how](https://goatcorp.github.io/faq/development#q-how-do-i-hot-reload-my-plugin)).

**api6** is for XivGlobal, which is not been tested and **api5** is for XivCN.

This plugin is unstable and may contains many potential bugs, use at your own risk.

国服用api5版本的.
